#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/polybar/launch.sh &
xsetroot -cursor_name left_ptr &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap           4

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       false

bspc config normal_border_color   "#161821"
bspc config focused_border_color  "#95c4ce"
bspc config active_border_color   "#6b7089"
bspc config presel_feedback_color "#95c4ce"

bspc config focus_follows_pointer true

bspc rule -r '*'
bspc rule -a qutebrowser desktop='^2'
bspc rule -a Firefox desktop='^2'
bspc rule -a Pcmanfm desktop='^6'
bspc rule -a Filezilla desktop='^6'
bspc rule -a Gimp desktop='^7'
bspc rule -a Inkscape desktop='^7'
bspc rule -a Zathura state=tiled
bspc rule -a mpv state=floating
bspc rule -a floating-st state=floating
