#! /bin/sh

sxhkd &
polybar main -r &
xsetroot -cursor_name left_ptr &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap           4

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

bspc config normal_border_color   "#161821"
bspc config focused_border_color  "#95c4ce"
bspc config presel_feedback_color "#95c4ce"

bspc config focus_follows_pointer true

bspc rule -r '*'
bspc rule -a qutebrowser desktop='^2'
